[TOC]

#### 5. Eclipse与异常处理

##### 5.1. 异常处理

- <font face="Arial" size=3>try</font><font face="楷体" size=4>与</font><font face="Arial" size=3>catch</font><font face="楷体" size=4>关键字：</font>

  ```java
  // 在程序中出现异常，就必须进行处理，处理格式如下：
  try (...) {// JDK1.7以后直接释放资源
      // 可能发生异常的代码段
  } catch (异常类型 对象) {
      // 异常的处理操作
  } catch (异常类型 对象) {
      // 异常的处理操作
  }...
  finally {
      // 异常的统一出口
  }
  ```

- <font face="楷体" size=4>异常处理过程分析：</font>

  - <font face="楷体" size=4>一旦产生异常，则系统会自动产生一个异常类的实例化对象</font>
  - <font face="楷体" size=4>此时如果存在了</font><font face="Arial" size=3>try</font><font face="楷体" size=4>语句，则会自动找到匹配的</font><font face="Arial" size=3>catch</font><font face="楷体" size=4>语句执行，如果没有异常处理，则程序退出，并由系统报告错误</font>
  - <font face="楷体" size=4>所有的</font><font face="Arial" size=3>catch</font><font face="楷体" size=4>根据方法的参数匹配异常类的实例化对象，如果匹配成功，则表示由此</font><font face="Arial" size=3>catch</font><font face="楷体" size=4>进行处理</font>

- <font face="Arial" size=3>finally</font><font face="楷体" size=4>关键字：</font>

  - <font face="楷体" size=4>在进行异常的处理之后，在异常的处理格式中还有一个</font><font face="Arial" size=3>finally</font><font face="楷体" size=4>语句，那么此语句将作为异常的统一出口，不管是否产生了异常，最终都要执行此段代码</font>

- <font face="楷体" size=4>什么是异常？</font>

  - <font face="楷体" size=4>异常是阻止当前方法或作用域继续执行的问题，在程序中导致程序中断运行的一些指令</font>

- <font face="Arial" size=3>throw</font><font face="楷体" size=4>和</font><font face="Arial" size=3>throws</font><font face="楷体" size=4>关键字：</font>

  - <font face="Arial" size=3>throws</font><font face="楷体" size=4>关键字主要在方法的声明上使用，表示方法中不处理异常，而交给调用处理。实际上对于</font><font face="Arial" size=3>Java</font><font face="楷体" size=4>程序来讲，如果没有加入任何的异常处理，默认由</font><font face="Arial" size=3>JVM</font><font face="楷体" size=4>进行异常的处理操作</font>
  - <font face="Arial" size=3>throws</font><font face="楷体" size=4>关键字表示在程序中手动抛出一个异常，因此从异常处理机制来看，所有的异常一旦产生之后，实际上抛出的就是一个异常类的实例化对象，那么此对象也可以由</font><font face="Arial" size=3>throw</font><font face="楷体" size=4>直接抛出</font>

- <font face="楷体" size=4>异常处理的语法法则：</font>

  - <font face="Arial" size=3>try</font><font face="楷体" size=4>语句不能单独存在，可以和</font><font face="Arial" size=3>catch、finally</font><font face="楷体" size=4>组成</font><font face="Arial" size=3>try..catch.finally、try...catch、try...finally</font><font face="楷体" size=4>三种结构，</font><font face="Arial" size=3>catch</font><font face="楷体" size=4>语句可以有一个或多个，</font><font face="Arial" size=3>finally</font><font face="楷体" size=4>语句最多一个，</font><font face="Arial" size=3>try、catch、finally</font><font face="楷体" size=4>这三个关键字均不能单独使用</font>
  - <font face="Arial" size=3>try、catch、finally</font><font face="楷体" size=4>三个代码块中变量的作用域分别独立而不能相互访问</font>
  - <font face="楷体" size=4>多个</font><font face="Arial" size=3>catch</font><font face="楷体" size=4>块时候，</font><font face="Arial" size=3>Java</font><font face="楷体" size=4>虚拟机会匹配其中一个异常类或子类，就执行这个</font><font face="Arial" size=3>catch</font><font face="楷体" size=4>块，而不会执行别的</font><font face="Arial" size=3>catch</font><font face="楷体" size=4>块</font>

##### 5.2. 自定义异常

- <font face="楷体" size=4>自定义异常类：</font><font face="Arial" size=3>CustomException</font>

  ```java
  /**
   * 自定义异常通常都是通过继承一个异常类来实现的
   * 1.Throwable
   * 2.Exception
   * 3.RuntimeException
   * 自定义异常通常的实现是重写父类的构造方法
   * 异常对象本身是没有实际功能，只是一个有意义的标识
   */
  public class CustomException extends Exception {
  	public CustomException() {
  		super();
  	}
  	
  	public CustomException(String message) {
  		super(message);
  	}
  }
  ```

- <font face="楷体" size=4>用户类：</font><font face="Arial" size=3>User</font>

  ```java
  /**
   * @description User类
   */
  public class User {
  	private String userName;
  	private String password;
  	private int age;
  	private String sex;
  
  	public User() {
  	}
  
  	public User(String userName, String password, int age, String sex) {
  		super();
  		this.userName = userName;
  		this.password = password;
  		this.age = age;
  		this.sex = sex;
  	}
  
  	public String getUserName() {
  		return userName;
  	}
  
  	public void setUserName(String userName) {
  		this.userName = userName;
  	}
  
  	public String getPassword() {
  		return password;
  	}
  
  	public void setPassword(String password) {
  		this.password = password;
  	}
  
  	public int getAge() {
  		return age;
  	}
  
  	public void setAge(int age) {
  		this.age = age;
  	}
  
  	public String getSex() {
  		return sex;
  	}
  
  	public void setSex(String sex) {
  		this.sex = sex;
  	}
  
  	@Override
  	public String toString() {
  		return "User [userName=" + userName + ", password=" + password + ", age=" + age + ", sex=" + sex + "]";
  	}
  
  }
  ```

- <font face="楷体" size=4>用户服务类：</font><font face="Arial" size=3>UserService</font>

  ```java
  /**
   * @description UserService类
   */
  public class UserService {
  	public User login(String userName, String password) throws CustomException {
  		if (!"admin".equals(userName)) {
  			throw new CustomException("用户名错误");
  		}
  		if (!"123456".equals(password)) {
  			throw new CustomException("密码错误");
  		}
  		
  		User user = new User("admin", "123456", 18, "男");
  		return user;
  	}
  }
  ```

- <font face="楷体" size=4>登录测试类（主函数）：</font><font face="Arial" size=3>LoginDemo</font>

  ```java
  import java.util.Scanner;
  
  /**
   * @description LoginDemo类
   */
  public class LoginDemo {
  	public static void main(String[] args) {
  		Scanner scanner = new Scanner(System.in);
  		System.out.println("请输入用户名：");
  		String name = scanner.nextLine();
  		System.out.println("请输入密码：");
  		String password = scanner.nextLine();
  		
  		UserService userService = new UserService();
  		try {
  			User user = userService.login(name, password);
  			System.out.println("登录成功");
  			System.out.println(user);
  		} catch (CustomException e) {
  			e.printStackTrace();
  		}
  
  		scanner.close();
  	}
  }
  ```

##### 5.3. 受检与非受检异常

- <font face="楷体" size=4>受检异常：</font><font face="Arial" size=3>Exception</font>

  - <font face="楷体" size=4>定义方法时必须声明所有可能会抛出的</font><font face="Arial" size=3>exception</font><font face="楷体" size=4>；在调用这个方法时，必须捕获它的</font><font face="Arial" size=3>checked exception</font><font face="楷体" size=4>，不然就得把它的</font><font face="Arial" size=3>exception</font><font face="楷体" size=4>传递下去；</font><font face="Arial" size=3>exception</font><font face="楷体" size=4>是从</font><font face="Arial" size=3>java.lang.Exception</font><font face="楷体" size=4>类衍生出来的。例如：</font><font face="Arial" size=3>IOException，SQLException</font>

- <font face="楷体" size=4>非受检异常：</font><font face="Arial" size=3>RuntimeException</font>

  - <font face="楷体" size=4>在定义方法时不需要声明会抛出的</font><font face="Arial" size=3>runtime exception</font><font face="楷体" size=4>；在调用这个方法时不需要捕获这个</font><font face="Arial" size=3>runtime exception</font><font face="楷体" size=4>；</font><font face="Arial" size=3>runtime exception</font><font face="楷体" size=4>是从</font><font face="Arial" size=3>java.lang.RuntimeException</font><font face="楷体" size=4>或</font><font face="Arial" size=3>java.lang.Error</font><font face="楷体" size=4>类衍生出来的。例如：</font><font face="Arial" size=3>NullPointerException，IndexOutOfBoundsException</font>

- <font face="楷体" size=4 color=blue>注意：</font><font face="Arial" size=3>assert</font><font face="楷体" size=4>关键字：表示断言</font>

  - <font face="楷体" size=4>当程序执行到某个固定的位置时，程序中的某个变量的取值肯定是预期的结果，那么这种操作可以使用断言完成</font>

    ```java
    // 格式
    public class AssertDemo {
    	public static void main(String[] args) {
    		int result = add(1, 10);
    		assert result == 10 : "结果不正确";
    	}
    	
    	private static int add(int a, int b) {
    		return a + b;
    	}
    }
    
    // 在eclipse中运行时需要对运行进行简单配置，配置Arguments中的VM arguments，配置为-ea
    ```

##### 5.4. <font color=blue>注意：</font>

- <font face="Arial" size=3>Throwable</font><font face="楷体" size=4>是异常的基类，分为</font><font face="Arial" size=3>Error</font><font face="楷体" size=4>和</font><font face="Arial" size=3>Exception</font><font face="楷体" size=4>，在编程中我们要关注</font><font face="Arial" size=3>Exception</font>
- <font face="Arial" size=3>Exception</font><font face="楷体" size=4>分为编译期异常（受检）和运行期异常（非受检）</font>
- <font face="楷体" size=4>异常会导致程序中断，无法继续执行</font>
- <font face="楷体" size=4>在开发中，我们需要把可能出现异常的代码使用</font><font face="Arial" size=3>try</font><font face="楷体" size=4>语句块包裹起来</font>
- <font face="楷体" size=4>处理异常可以让程序保持运行状态</font>
- <font face="Arial" size=3>catch</font><font face="楷体" size=4>可以有多个，顺序为从子类到父类，大的放后面，小的放前面</font>